name: PHP CI/CD
on:
  push:
    branches:
      - main  # 监控main分支的推送

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  Deploy:
    uses: luzhengfei/devops/.github/workflows/deploy-php.yml@main
    inputs:
      # 应用名称
      APP_NAME: laravel-backend-project
      # 指定PHP镜像版本，目前实时编译最新的
      #IMAGE_NAME : prod-php8.4-v1

      # AWS 配置
      AWS_ACCESS_KEY_ID: ${{ env.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ env.AWS_SECRET_ACCESS_KEY }}

      # 邮件配置
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      OWNER_EMAIL: 981864142@qq.com

