name: PHP CI/CD
on:
  push:
    branches:
      - main  # 监控main分支的推送

jobs:
  Deploy:
    uses: luzhengfei/devops/.github/workflows/deploy-php.yml@main
    with:
      # 应用名称
      APP_NAME: laravel-backend-project
      # 指定PHP镜像版本，目前实时编译最新的.
      #IMAGE_NAME : prod-php8.4-v1