name: PHP CI/CD
on:
  push:
    branches:
      - main  # 监控main分支的推送
env:
  APP_NAME: ${{ secrets.APP_NAME }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  #AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}           # set this to your Amazon ECR repository name
  ECS_SERVICE: ${{ secrets.ECS_SERVICE }}                 # set this to your Amazon ECS service name
  ECS_CLUSTER: ${{ secrets.ECS_CLUSTER }}                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: ${{ secrets.ECS_TASK_DEFINITION }}
  #ECS_TASK_DEFINITION_NAME: ${{ secrets.ECS_TASK_DEFINITION_NAME }}
  #ECS_TASK_DEFINITION_VER: ${{ secrets.ECS_TASK_DEFINITION_VER }}
  CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}

jobs:
  Deploy:
    uses: luzhengfei/devops/.github/workflows/deploy-php.yml@main
    with:
      APP_NAME: laravel-backend-project